// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type Movie struct {
	ID        int32
	Title     string
	Director  sql.NullString
	Year      sql.NullInt32
	Genre     sql.NullString
	Rating    sql.NullString
	CreatedAt time.Time
}

type User struct {
	ID        int32
	Username  string
	Password  string
	CreatedAt time.Time
}
